name: Deploy Frontend

on:
  push:
    branches:
      - master # Or any branch you want to trigger the deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
            cd blog-frontend
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest

            # Stop and remove existing containers
            docker stop blog-frontend || true
            docker rm blog-frontend || true

            # Run the Docker container with the correct name and configuration
            docker run -d --name blog-frontend -p 8080:80 ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest

            # Clean up unused images
            docker image prune -f
