name: Deploy Frontend

on:
  push:
    branches:
      - master # Or any branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest .

      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest

      - name: Set correct permissions on EC2 target directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.EC2_USER }}
            chmod 755 /home/${{ secrets.EC2_USER }}

      # - name: Copy docker-compose.yml to EC2
      #   uses: appleboy/scp-action@v0.1.1
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     source: "./docker-compose.yml"
      #     target: "/home/${{ secrets.EC2_USER }}/docker-compose.yml"
      #     port: 22
      #     overwrite: true
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd blog-frontend
            sudo docker-compose stop
            sudo docker-compose rm -f
            sudo docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest
            sudo docker-compose up -d

        # echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
        # docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/blog-frontend:latest
        # cd /home/${{ secrets.EC2_USER }}
        # chmod 644 docker-compose.yml
        # docker-compose -f docker-compose.yml up -d frontend
